### ISSUE TITLE
Published sample app doesn't display movies

### ISSUE THREAD

**Issue by CamSoper** [NERDStack/nerd-cli#21]
Created a new sample app.  Runs locally fine.  Published to Azure App Service with the same DocumentDB URI and key.  After building, application runs, but finds no movies.  Displays only page header.

http://nerd-doc-sample.azurewebsites.net/

Note that the **movies** REST request seems to get a 404 with the following payload:

```json
{"code":"NotFound","message":"Message: {\"Errors\":[\"Owner resource does not exist\"]}\r\nActivityId: 150aeb89-d082-48dd-bd53-5476dee3c26c, Request URI: /apps/9a95be2d-2c53-4a03-acb9-f58629f67ac3/services/01c5dc57-532f-42f1-9a8b-dca55b4b04a5/partitions/16bda4b2-89fb-472c-8ede-2617078731bf/replicas/131292931880136616s"}
```

**Comment by tstringer** [comment]
Thanks for creating this issue! What OS are you running this on? What version of the nerd cli is this (`nerd --version`)?

I'll take a look and try to repro this.

**Comment by CamSoper** [comment]
Windows 10.  0.4.1.  

I'll let you into my Azure subscription if you want to take a look.  Hit me up on Skype if you want to debug together.  My schedule today is pretty open.  Calendar is up-to-date.

**Comment by tstringer** [comment]
I think I know what might've happened here. Basically when you run `nerd install`, it pulls down the nerdy-movies sample web app. Part of the process during the `install` phase is to modify the database connection configuration (database name and collection name for DocumentDB). This leaves the working directory in the correct state, but the git repo (which is the underlying mechanism for a `nerd publish`) is in a state where this change is uncommitted.

So after you run `nerd install`, you should be running a `git add` and `git commit` so that your repo now includes the updated changes. After all, `nerd publish` just sets up the deployment for the Azure Web App, it's really a `git push` that subsequently deploys code.

I just tested this out in my environment, this does appear to be a working workflow. At the most here, perhaps we should be more explicit of what you need to do.

Closing this for now, let me know if I missed something and there is another issue here. Thanks! 👍
