### ISSUE TITLE
"cli run" doesn't work on Windows

### ISSUE THREAD

**Issue by jplane** [NERDStack/nerd-cli#7]
Doesn't seem to like the "start-local-win" command in package.json of nerdy movies site. Here's the error I get:

_"'.' is not recognized as an internal or external command, operable program or batch file."_

To repro I manually edited the run.js file to use the Windows specific command (run isn't platform aware yet).

**Comment by tstringer** [comment]
@tripdubroot can you take a look at this?

**Comment by tstringer** [comment]
I think this was due to how the npm script was written. I have appended `powershell.exe` to the script command (found in this commit: https://github.com/NERDStack/nerdy-movies/commit/ea3fecc4365a7349e9d38d64aa58853391f3fbae). It looks like that got past the error. At this point, we still need to figure out how to determine the platform and run based off of that, as well as the windows script should use the remote documentdb account.

Can you test this on windows again and verify that you're no longer getting the error?

**Comment by tstringer** [comment]
I was able to get this working, as well as now you can run `nerd run` on any platform, and the NERD cli will determine which npm script to run based off of your platform. Here is the code that makes that possible: https://github.com/NERDStack/nerd-cli/blob/master/src/run.js#L5-L6
